apiVersion: {{ .Values.service.apiversion }}
kind: Service
metadata:
  labels:
    app: ph-ee-connector-ams-mifos
  name: ph-ee-connector-ams-mifos
spec:
  ports:
    - name: port
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: ph-ee-connector-ams-mifos
  sessionAffinity: None
  type: ClusterIP